# Generated by Django 5.1 on 2024-09-07 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_document_remove_student_student_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_duration', models.TextField()),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('class_per_week', models.PositiveIntegerField()),
                ('class_days', models.TextField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='user.trainer')),
            ],
        ),
    ]
