# Generated by Django 5.1 on 2024-09-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('user', '0002_document_remove_student_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_days',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_per_week',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_duration',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_fee',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_name',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='course.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='course_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
