# Generated by Django 5.1 on 2024-09-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_student_trainer_name_student_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
